
== NFS Subdirectory External Provisioner Helm Chart

. Choose a VM to install the NFS Server
. sudo apt install nfs-kernel-server
. create a folder for NFS Server to store data
. sudo mkdir -p /srv/kubernetes/volume
. change the ownership to nobody:nogroup
. sudo chown -R nobody:nogroup /srv/kubernetes/
. sudo chmod -R 777 /srv/kubernetes/
. sudo vi /etc/exports
. add the following line (Grant NFS Share Access to Client Systems) +
/srv/kubernetes/   192.168.59.0/24(rw,no_root_squash, no_subtree_check,insecure)

sometimes due to NAT actual client IP is not sent to the server, so use *

/srv/kubernetes/   *(rw,no_root_squash,no_subtree_check,insecure)
 
[start=10]
. Export the NFS Share directory
 
 sudo exportfs -ar
 
 sudo systemctl restart nfs-kernel-server

[start=11]
. Allow NFS Access through the Firewall

For the client to access the NFS share, you need to allow access through the firewall otherwise, accessing and mounting the shared directory will be impossible. To achieve this run the command:

 sudo ufw allow from 192.168.43.0/24 to any port nfs
 
 [start=12]
. Reload or enable the firewall (if it was turned off) and check the status of the firewall. Port 2049, which is the default file share, should be opened.

$ sudo ufw enable
$ sudo ufw status

. https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/README.md

. helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

. helm repo update

. helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner  --values nfs-provisioner-values.yaml -n nfs-system --create-namespace

. helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=172.16.16.100 \
    --set nfs.path=/srv/kubernetes/volume

