kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cd-jenkins-deployment-role
rules:
- apiGroups: ["", "extensions", "apps", "networking.k8s.io"]
  resources: ["namespaces", "deployments", "replicasets", "pods", "services", "ingresses"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"] # You can also use ["*"]
