== Install Jenkins Using Helm

. helm repo add jenkinsci https://charts.jenkins.io
. helm repo update

  The helm charts in the Jenkins repo can be listed with the command:

[start=3]
. helm search repo jenkinsci
. Edit the jenkins-values.yaml file for your need. I am using ingress to access the Jenkins Admin UI
. kubectl create ns jenkins
. PVC must be created befor hand to enable persistence
. kubectl apply -f jenkins-pvc.yaml
. helm install cd-jenkins -n jenkins --values jenkins-values.yaml --set controller.adminPassword=MySecretPwd jenkinsci/jenkins


.Kubernetes Pod as Jenkins Build Agent
NOTE: By defauly these pods are launched with default service account from its namespace. The default service account has no ClusterRole 
to deploy application into k8s. So we have to follow these steps to give required permissions to these Build Agent Pods to deploy application into k8s.
In local dev/test for quick testing you can grant cluster-admin role to serviceaccount=jenkins:default as

[start=9]
. kubectl create clusterrolebinding jenkins-sa-default  --clusterrole cluster-admin --serviceaccount=jenkins:default

But this will grant excessive permissions to serviceaccount=jenkins:default.

The preferred way to do this

[start=10]
. create a ServiceAccount jenkins-agent in jenkins namespace ( the ServiceAccount=cd-jenkins created by helm deployment of jenkins )
. create a ClusterRole using the file cd-jenkins-deployment-role.yaml
. Now create a ClusterRoleBinding  cd-jenkins-ClusterRoleBinding using the ServiceAccount cd-jenkins and cd-jenkins-deployment-role
. kubectl create clusterrolebinding cd-jenkins-ClusterRoleBinding  --clusterrole cd-jenkins-deployment-role --serviceaccount=jenkins:cd-jenkins



. To search the RoleBinding and ClusterRoleBinding for service account jenkins-agent execute the following command

kubectl get rolebindings,clusterrolebindings --all-namespaces -o custom-columns='KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,SERVICE_ACCOUNTS:subjects[?(@.kind=="ServiceAccount")].name' | grep "cd-jenkins"
